version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:16
    working_directory: ~/app
    environment:
      TZ: Europe/Berlin
    steps:
      - checkout
      - run:
          name: Install npm wee
          command: npm install
      - run:
          name: Test
          command: npm test

# Orchestrate our job run sequence
workflows:
  test:
    jobs:
      - test
