// ---- Generated by gulp taskRef ----
export {IBaseRef} from './api/IBaseRef';
export {IBuildOptions} from './api/IBuildOptions';
export {IClassRef} from './api/IClassRef';
export {IEntityRef} from './api/IEntityRef';
export {ILookupRegistry} from './api/ILookupRegistry';
export {IPropertyExtentions} from './api/IPropertyExtentions';
export {IPropertyRef} from './api/IPropertyRef';
export {ISchemaRef} from './api/ISchemaRef';

export {Entity} from './decorators/Entity';
export {Property} from './decorators/Property';
export {Embeddable} from './decorators/Embeddable';
export {PropertyOf} from './decorators/PropertyOf';
export {Schema} from './decorators/Schema';

export {
  Hostname,
  HOSTNAME_RFC1034_REGEX,
  IHostnameOptions,
  HOSTNAME_RFC952_REGEX
} from './decorators/validate/Hostname';

export {Ip4, IP4_REGEX, IIp4Options} from './decorators/validate/Ip4';
export {Ip6, IP6_REGEX, IIp6Options} from './decorators/validate/Ip6';
export {IsEmail, MAIL_REGEX, IIsEmailOptions} from './decorators/validate/IsEmail';
export {Regex, IRegexOptions} from './decorators/validate/Regex';
export {Required, IRequiredOptions} from './decorators/validate/Required';

export {AbstractRef} from './lib/AbstractRef';
export {AnnotationsHelper} from './lib/AnnotationsHelper';
export {ClassRef} from './lib/ClassRef';
export {
  METATYPE_SCHEMA,
  METATYPE_ENTITY,
  METATYPE_PROPERTY,
  METATYPE_CLASS_REF,
  METADATA_TYPE,
  DEFAULT_NAMESPACE,
  XS_ANNOTATION_OPTIONS_CACHE,
  MERGE_TYPE, IMinMax, ClassType,
  __CLASS__, __NS__,
  C_EVENT_ADD, C_EVENT_REMOVE, C_EVENT_UPDATE,
  C_PROP_NAME, CLASS_TYPE, GLOBAL_NAMESPACE, JS_DATA_TYPES, JS_PRIMATIVE_TYPES,
  METADATA_REGISTRY, METATYPE_OBJECT,
  OPT_CREAT_AND_COPY, REFLECT_DESIGN_TYPE, STATE_KEY,
  T_STRING, XS_DATA_TYPES,
  XS_DEFAULT_CLASSES, XS_DEFAULT_SCHEMA,
  METADATA_AND_BIND_TYPE,
  XS_ID_SEPARATOR, BINDING_SCHEMA_ENTITY, BINDING_SCHEMA_CLASS_REF
} from './lib/Constants';

export {DataContainer} from './lib/DataContainer';
export {DRAFT_07} from './lib/json-schema/Constants';
export {IJsonSchemaSerializeOptions} from './lib/json-schema/IJsonSchemaSerializeOptions';
export {IJsonSchemaSerializer} from './lib/json-schema/IJsonSchemaSerializer';
export {IJsonSchemaUnserializeOptions} from './lib/json-schema/IJsonSchemaUnserializeOptions';
export {IJsonSchemaUnserializer} from './lib/json-schema/IJsonSchemaUnserializer';
export {IParseOptions} from './lib/json-schema/IParseOptions';
export {JsonSchema} from './lib/json-schema/JsonSchema';

export {
  IJsonSchema7,
  IJsonSchema7Definition,
  hasClassInDefinition,
  hasClassPropertiesInDefinition,
  IJsonSchema7TypeName,
  JSON_SCHEMA_7_TYPES
} from './lib/json-schema/JsonSchema7';

export {JsonSchema7Serializer} from './lib/json-schema/JsonSchema7Serializer';
export {JsonSchema7Unserializer} from './lib/json-schema/JsonSchema7Unserializer';
export {LookupRegistry} from './lib/LookupRegistry';
export {IAbstractOptions} from './lib/options/IAbstractOptions';
export {IEntityOptions} from './lib/options/IEntityOptions';
export {IObjectOptions} from './lib/options/IObjectOptions';
export {IPropertyOptions} from './lib/options/IPropertyOptions';
export {ISchemaOptions} from './lib/options/ISchemaOptions';
export {DefaultEntityRef} from './lib/registry/DefaultEntityRef';
export {DefaultNamespacedRegistry} from './lib/registry/DefaultNamespacedRegistry';
export {DefaultPropertyRef} from './lib/registry/DefaultPropertyRef';
export {MetadataRegistry} from './lib/registry/MetadataRegistry';
export {RegistryFactory} from './lib/registry/RegistryFactory';
export {SchemaRef} from './lib/SchemaRef';
export {SchemaUtils} from './lib/SchemaUtils';
export {DefaultValidator, IValidatorEntry} from './lib/validation/DefaultValidator';
export {IValidateOptions} from './lib/validation/IValidateOptions';
export {IValidationError} from './lib/validation/IValidationError';
export {IValidationMessage} from './lib/validation/IValidationMessage';
export {IValidationMetadataArgs} from './lib/validation/IValidationMetadataArgs';
export {IValidationOptions} from './lib/validation/IValidationOptions';
export {IValidationResult} from './lib/validation/IValidationResult';
export {IValidator} from './lib/validation/IValidator';
export {Validator, validate_function} from './lib/validation/Validator';
